const SET_CHOSEN_MENU = 'SET_CHOSEN_MENU';

// todo list - get
const FETCH_TODO_LIST_PENDING = 'FETCH_TODO_LIST_PENDING';
const FETCH_TODO_LIST_FAILED = 'FETCH_TODO_LIST_FAILED';
const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS';

// todo list - post
const POST_TODO_LIST_PENDING = 'POST_TODO_LIST_PENDING';
const POST_TODO_LIST_FAILED = 'POST_TODO_LIST_FAILED';
const POST_TODO_LIST_SUCCESS = 'POST_TODO_LIST_SUCCESS';

// todo priorities fetches
const FETCH_TODO_PRIORITIES_PENDING = 'FETCH_TODO_PRIORITIES_PENDING';
const FETCH_TODO_PRIORITIES_FAILED = 'FETCH_TODO_PRIORITIES_FAILED';
const FETCH_TODO_PRIORITIES_SUCCESS = 'FETCH_TODO_PRIORITIES_SUCCESS';

const ActionTypes = {
  SET_CHOSEN_MENU,
  FETCH_TODO_LIST_PENDING,
  FETCH_TODO_LIST_FAILED,
  FETCH_TODO_LIST_SUCCESS,
  POST_TODO_LIST_PENDING,
  POST_TODO_LIST_FAILED,
  POST_TODO_LIST_SUCCESS,
  FETCH_TODO_PRIORITIES_PENDING,
  FETCH_TODO_PRIORITIES_FAILED,
  FETCH_TODO_PRIORITIES_SUCCESS
};
export default ActionTypes;
